python fitting_model_params.py --N 1000 -df 0 --fitting &
python fitting_model_params.py --N 1000 -df 1 --fitting &
python fitting_model_params.py --N 1000 -df 2 --fitting &
python fitting_model_params.py --N 1000 -df 3 --fitting &
python fitting_model_params.py --N 1000 -df 4 --fitting &
python fitting_model_params.py --N 1000 -df 5 --fitting &
python fitting_model_params.py --N 1000 -df 6 --fitting &
python fitting_model_params.py --N 1000 -df 7 --fitting &
python fitting_model_params.py --N 1000 -df 8 --fitting &
python fitting_model_params.py --N 1000 -df 9 --fitting &
python fitting_model_params.py --N 1000 -df 10 --fitting &
python fitting_model_params.py --N 1000 -df 11 --fitting &
python fitting_model_params.py --N 1000 -df 12 --fitting &
